# Generated by Django 4.1.5 on 2023-02-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
